// <auto-generated />
using System;
using HojasPersonaje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HojasPersonaje.Migrations
{
    [DbContext(typeof(ClaseContexto))]
    [Migration("20251229223951_AgregarCampoTablaPrincipioCronica")]
    partial class AgregarCampoTablaPrincipioCronica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HojasPersonaje.Entidades.Atributo_Hoja_Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Astucia")
                        .HasColumnType("int");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int>("Compostura")
                        .HasColumnType("int");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Fuerza")
                        .HasColumnType("int");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<int>("Manipulacion")
                        .HasColumnType("int");

                    b.Property<int>("Resistencia")
                        .HasColumnType("int");

                    b.Property<int>("Resolucion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Atributos_Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Biografia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apariencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad_Aparente")
                        .HasColumnType("int");

                    b.Property<int>("Edad_Real")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha_Muerte")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Historia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<string>("Rasgos_Distintivos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Biografias");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Clan_Bane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compulsion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VampiroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VampiroId");

                    b.ToTable("Clan_Banes");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Conviccion_Piedras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Convicciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<string>("Piedras_Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Convicciones_Piedras");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Cronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dungeon_MasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Cronica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Cronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais_Cronica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dungeon_MasterId");

                    b.ToTable("Cronicas");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_Disciplina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina_Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Disciplinas_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina_Vampiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("VampiroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("VampiroId");

                    b.ToTable("Disciplinas_Vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Especialidad_Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.ToTable("Especialidades_Habilidades");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Experiencia_Hoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia_Gastada")
                        .HasColumnType("int");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Experiencias_Hoja");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Flaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Flaws");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicismo")
                        .HasColumnType("int");

                    b.Property<int>("Actuacion")
                        .HasColumnType("int");

                    b.Property<int>("Animal_Ken")
                        .HasColumnType("int");

                    b.Property<int>("Armas_Fuego")
                        .HasColumnType("int");

                    b.Property<int>("Astucia")
                        .HasColumnType("int");

                    b.Property<int>("Atletismo")
                        .HasColumnType("int");

                    b.Property<int>("Ciencia")
                        .HasColumnType("int");

                    b.Property<int>("Conduccion")
                        .HasColumnType("int");

                    b.Property<int>("Consciencia")
                        .HasColumnType("int");

                    b.Property<int>("Crafteo")
                        .HasColumnType("int");

                    b.Property<int>("Etiqueta")
                        .HasColumnType("int");

                    b.Property<int>("Finanzas")
                        .HasColumnType("int");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("Insight")
                        .HasColumnType("int");

                    b.Property<int>("Intimidacion")
                        .HasColumnType("int");

                    b.Property<int>("Investigacion")
                        .HasColumnType("int");

                    b.Property<int>("Latrocinio")
                        .HasColumnType("int");

                    b.Property<int>("Liderazgo")
                        .HasColumnType("int");

                    b.Property<int>("Medicina")
                        .HasColumnType("int");

                    b.Property<int>("Melee")
                        .HasColumnType("int");

                    b.Property<int>("Ocultismo")
                        .HasColumnType("int");

                    b.Property<int>("Pelea")
                        .HasColumnType("int");

                    b.Property<int>("Persuasion")
                        .HasColumnType("int");

                    b.Property<int>("Politica")
                        .HasColumnType("int");

                    b.Property<int>("Sigilo")
                        .HasColumnType("int");

                    b.Property<int>("Subterfugio")
                        .HasColumnType("int");

                    b.Property<int>("Supervivencia")
                        .HasColumnType("int");

                    b.Property<int>("Tecnologia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.HabilidadesPersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("HabilidadesPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidades_Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Habilidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Habilidades_Disciplina");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Hoja_Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CronicaId")
                        .HasColumnType("int");

                    b.Property<string>("Desire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generacion")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_DepredadorId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_VampiroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CronicaId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("Tipo_DepredadorId");

                    b.HasIndex("Tipo_VampiroId");

                    b.ToTable("Hojas_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Lista_Amigos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_Amigos")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario1Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario1Id");

                    b.HasIndex("Usuario2Id");

                    b.ToTable("Listas_Amigos");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Merito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Meritos");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Nota_Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CronicaId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CronicaId");

                    b.HasIndex("JugadorId");

                    b.ToTable("Notas_Adicionales");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Notas_Principales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Notas_Principales");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Posesiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<string>("Posesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Posesiones");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Principio_Cronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CronicaId")
                        .HasColumnType("int");

                    b.Property<string>("Principios_Cronica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CronicaId");

                    b.ToTable("Principios_Cronicas");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Tipo_Depredador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Depredador");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Vampiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vampiros");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Hoja_PersonajeId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hoja_PersonajeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Atributo_Hoja_Personaje", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Atributos_Hoja_Personaje")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Background", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Backgrounds")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Biografia", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Biografias")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Clan_Bane", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Vampiro", "Vampiro")
                        .WithMany("Clanes_Banes")
                        .HasForeignKey("VampiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Conviccion_Piedras", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Convicciones_Piedras")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Cronica", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Usuario", "Dungeon_Master")
                        .WithMany("Cronicas")
                        .HasForeignKey("Dungeon_MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dungeon_Master");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina_Personaje", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Disciplina", "Disciplina")
                        .WithMany("Disciplina_Personajes")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Disciplina_Personajes")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina_Vampiro", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Disciplina", "Disciplina")
                        .WithMany("Disciplina_Vampiro")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Vampiro", "Vampiro")
                        .WithMany("Disciplina_Vampiro")
                        .HasForeignKey("VampiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Especialidad_Habilidad", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Habilidad", "Habilidad")
                        .WithMany("Especialidades_Habilidad")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habilidad");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Experiencia_Hoja", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Experiencias_Hojas")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Flaw", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany()
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidad", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Habilidades")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.HabilidadesPersonaje", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Habilidades_Disciplina", "Disciplina")
                        .WithMany("HabilidadesPersonajes")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Personaje")
                        .WithMany("HabilidadesPersonajes")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidades_Disciplina", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Disciplina", "Disciplina")
                        .WithMany("Habilidades_Disciplina")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Hoja_Personaje", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Cronica", "Cronica")
                        .WithMany("Vampiros")
                        .HasForeignKey("CronicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Usuario", "Jugador")
                        .WithMany("Hojas_Personaje")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Tipo_Depredador", "Tipo_Depredador")
                        .WithMany("Hojas_Personaje")
                        .HasForeignKey("Tipo_DepredadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Vampiro", "Tipo_Vampiro")
                        .WithMany("Hojas_Personaje")
                        .HasForeignKey("Tipo_VampiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cronica");

                    b.Navigation("Jugador");

                    b.Navigation("Tipo_Depredador");

                    b.Navigation("Tipo_Vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Lista_Amigos", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Usuario", "Usuario1")
                        .WithMany()
                        .HasForeignKey("Usuario1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("Usuario2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Merito", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Meritos")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Nota_Adicional", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Cronica", "Cronica")
                        .WithMany("Notas_Adicionales")
                        .HasForeignKey("CronicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Entidades.Usuario", "Jugador")
                        .WithMany("Notas_Adicionales")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cronica");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Notas_Principales", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Notas_Principales")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Posesiones", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Posesiones")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Principio_Cronica", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Cronica", "Cronica")
                        .WithMany("Principios_Cronica")
                        .HasForeignKey("CronicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cronica");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Weapon", b =>
                {
                    b.HasOne("HojasPersonaje.Entidades.Hoja_Personaje", "Hoja_Personaje")
                        .WithMany("Weapons")
                        .HasForeignKey("Hoja_PersonajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoja_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Cronica", b =>
                {
                    b.Navigation("Notas_Adicionales");

                    b.Navigation("Principios_Cronica");

                    b.Navigation("Vampiros");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Disciplina", b =>
                {
                    b.Navigation("Disciplina_Personajes");

                    b.Navigation("Disciplina_Vampiro");

                    b.Navigation("Habilidades_Disciplina");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidad", b =>
                {
                    b.Navigation("Especialidades_Habilidad");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Habilidades_Disciplina", b =>
                {
                    b.Navigation("HabilidadesPersonajes");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Hoja_Personaje", b =>
                {
                    b.Navigation("Atributos_Hoja_Personaje");

                    b.Navigation("Backgrounds");

                    b.Navigation("Biografias");

                    b.Navigation("Convicciones_Piedras");

                    b.Navigation("Disciplina_Personajes");

                    b.Navigation("Experiencias_Hojas");

                    b.Navigation("Habilidades");

                    b.Navigation("HabilidadesPersonajes");

                    b.Navigation("Meritos");

                    b.Navigation("Notas_Principales");

                    b.Navigation("Posesiones");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Tipo_Depredador", b =>
                {
                    b.Navigation("Hojas_Personaje");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Usuario", b =>
                {
                    b.Navigation("Cronicas");

                    b.Navigation("Hojas_Personaje");

                    b.Navigation("Notas_Adicionales");
                });

            modelBuilder.Entity("HojasPersonaje.Entidades.Vampiro", b =>
                {
                    b.Navigation("Clanes_Banes");

                    b.Navigation("Disciplina_Vampiro");

                    b.Navigation("Hojas_Personaje");
                });
#pragma warning restore 612, 618
        }
    }
}
